networks:
  default:
    name: nas-network

services:
  alpine:
    container_name: nas-server
    build: .
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    ports:
      - "2049:2049" 
    volumes:
      - ${LOCAL_DIRECTORY:-/fileshare}:${SHARED_DIRECTORY:-/nfsshare}
    environment:
      SHARED_DIRECTORY: "${SHARED_DIRECTORY:-/nfsshare}" 
